### ISSUE TITLE
Loading Commute error

### ISSUE THREAD

**Issue by ngp9702** [SamLewis0602/MMM-Traffic#30]
I believe my issue is with the api code, I have one but i dont think it is working. I tried posting it into that weblink you mentioned in another thread, but it told me that my api key was invalid. Any suggestion? Ive double and triple checked the actual module files and everything appears to match yours as far as i can tell. When i run the program, it never loads, only says "Loading commute"
The terminal window outputs this when it tries to load the module, 
     "Whoops! There was an uncaught exception...
      TypeError: Cannot read property 'legs' of undefined
         at Request._callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_helper.js:21:39)
         at Request.self.callback (/home/pi/MagicMirror/modules/MMM-               Traffic/node_modules/request/request.js:187:22)
       at emitTwo (events.js:106:13)
       at Request.emit (events.js:191:7)
       at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-   Traffic/node_modules/request/request.js:1048:10)
       at emitOne (events.js:96:13)
       at Request.emit (events.js:188:7)
       at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:969:12)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no   internet connection?
       If you think this really is an issue, please open an issue on GitHub:           https://github.com/MichMich/MagicMirror/issues
"

**Comment by SamLewis0602** [comment]
This stems directly from a bad API key. If your key is invalid, the response will not have the "legs" property because the Maps API is returning an error instead of an actual response. You need to create a working key, or ensure that the key that you pasted into your config is correct.
