### ISSUE TITLE
uncaught exception.

### ISSUE THREAD

**Issue by Sillec123** [SamLewis0602/MMM-Traffic#32]
Whoops! There was an uncaught exception...
TypeError: Cannot read property 'legs' of undefined
    at Request._callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_helper.js:47:55)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by iRazoR** [comment]
Same Problem here. Just installed the Module as written in the Readme and changed the config but no success.

**Comment by SamLewis0602** [comment]
See #10 to test API key.

**Comment by iRazoR** [comment]
Unbelievable.... Thanks for the link, I was looking for somethng to test the API Key. That solved my Problem.

**Comment by SamLewis0602** [comment]
No problem, I really need to catch that error and be more descriptive about what's going on. Enjoy the module!
