### ISSUE TITLE
has no legs

### ISSUE THREAD

**Issue by StupiduserIAM** [SamLewis0602/MMM-Traffic#43]
After following the directions the module worked perfectly.
But after a few config changes I am getting "Loading Commute..." but it never loads.

Upon exiting the MagicMirror I see this in the terminal window. Node_helper has Legs in it but the Request.js does not contain Legs variable.

Please advise.

Whoops! There was an uncaught exception...
TypeError: Cannot read property 'legs' of undefined
    at Request._callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_helper.js:31:45)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1126:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1046:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)

**Comment by SamLewis0602** [comment]
Does this happen every time you restart your mirror since you made those config changes?

**Comment by SamLewis0602** [comment]
Sorry for the delayed response, I was on vacation :)

**Comment by StupiduserIAM** [comment]
I blew it out and rebuilt it. Without your module this time. Sorry. I will copy my SD card and then I can try again.
