### ISSUE TITLE
TypeError: Cannot read property 'legs' of undefined at Request._callback 

### ISSUE THREAD

**Issue by CarnalMischief** [SamLewis0602/MMM-Traffic#81]
Hi, It might be me but all i'm getting is 'Loading Commute...'. I've checked my API key (here https://maps.googleapis.com/maps/api/directions/) and it's working fine.

Running on a Raspberry Pi 2 & 3b with MagicMirror 2.11.0 as per install instructions, I get his error:-

[2020-04-09 20:16:04.980] [LOG]    Whoops! There was an uncaught exception...
[2020-04-09 20:16:04.981] [ERROR]  TypeError: Cannot read property 'legs' of undefined
    at Request._callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_helper.js:29:36)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-04-09 20:16:04.989] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-04-09 20:16:04.990] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
^C[2020-04-09 20:16:10.788] [LOG]    Shutting down server...

Thanks

**Comment by SamLewis0602** [comment]
Are you on the latest version of MMM-Traffic? Run a `git pull` to make sure. The latest version should give more info in the UI on what the error is rather than just saying `Loading...`

**Comment by CarnalMischief** [comment]
Hi,
Thanks for getting back to me.

I did a 'git pull' inside the module folder:-

pi@raspberrypi:~/MagicMirror/modules $ cd MMM-Traffic
pi@raspberrypi:~/MagicMirror/modules/MMM-Traffic $ git pull
Already up to date.
pi@raspberrypi:~/MagicMirror/modules/MMM-Traffic $

Then ran the Mirror again, but I'm still getting the same error.

[2020-05-22 22:06:10.840] [LOG]    Whoops! There was an uncaught exception...
[2020-05-22 22:06:10.844] [ERROR]  TypeError: Cannot read property 'legs' of undefined
    at Request._callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_helper.js:29:36)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-05-22 22:06:10.857] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-05-22 22:06:10.865] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

The API test page I was using before has been moved / stopped working. Maybe Google have changed things at their end.

**Comment by CarnalMischief** [comment]
Hi
Although the UI wasn’t showing any additional info. Something has changed at Googles end.
I used your sample config as a base and slowly made changes to resemble my config till it stopped working.

It broke on ‘waypoints:’. So I google mapped my journey and changed the waypoint name to that now showing in the Google Maps journey and it’s working again.

Thanks for your help.

**Comment by SamLewis0602** [comment]
Thanks for the log! There must be another error case with the waypoints that I missed, I will look into it so people don't get stuck on Loading...
Glad you got it working!
